#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if (( $+commands[nvim] )); then
  typeset -xg EDITOR=nvim
else
  typeset -xg EDITOR=vim
fi

typeset -xg LANG=en-us.UTF-8
typeset -xg LC_CTYPE=en_US.UTF-8
typeset -xg LC_ALL=en_US.UTF-8
