# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
DEFAULT_USER="acunsolo"
# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.oh-my-zsh-custom

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    # Common
    git
    git-flow
    history
    man
    rsync
    sudo
    themes
    tmux
    tmuxinator
    zsh-autosuggestions
    zsh_reload
    zsh-syntax-highlighting
)

# FZF
if (( $+commands[fzf] )); then
    plugins+=(fzf)
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .snapshots --exclude .git'
    export FZF_DEFAULT_OPTS='--ansi --reverse --bind ctrl-f:page-down,ctrl-b:page-up'
fi
# Load custom scripts before oh my zsh initialization
# (setting plugins and all)
for config_file ($ZSH_CUSTOM/*.pre-zsh(N)); do
    source $config_file
done
unset config_file

source $ZSH/oh-my-zsh.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

_autoload_custom() {
    if [[ -d $1 ]]; then
        local -a f
        # ^/ Not directories
        # N -> Set NULL_GLOB
        # D -> Set DOT_GLOB
        # :A -> realpath (follow symlinks)
        f=( $1/*(^/ND:A) )
        [[ $#f -ne 0 ]] && autoload -Uz $f
    fi
}

_autoload_custom ~/.zsh-functions
_autoload_custom ~/.zsh-local-functions

setopt rmstarwait
setopt autonamedirs
setopt noclobber
setopt appendcreate

if [[ -d ~/.dotfiles ]]; then
    alias dot='cd ~/.dotfiles'
fi

# Turn off kube prompt
KUBE_PS1_ENABLED=false

path=(~/bin $path)
typeset -U path

# Use NeoVim instead of Vim
if (( $+commands[nvim] )); then
    alias vim='nvim'
    export EDITOR=nvim
fi

fpath=($fpath ~/.zsh/completion)
autoload -Uz compinit && compinit -i

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Start or attach to a tmux session with the given name ('main' as default)
function txa() {
    tmux new-session -A -s ${1:-main}
}

# Directiries
code=~/code
